services:
  integration-test-cedar-server:
    image: docker.io/svenstaro/miniserve
    ports:
      - "18999:18999"
    volumes:
      - ./testdata:/data:ro,Z
    command: ["/data", "--port", "18999"]

  integration-test-treetop-server:
    image: ${TREETOP_REST_IMAGE:-ghcr.io/treetop-policy-engine/treetop-rest:v0.0.12}
    container_name: integration-test-treetop-server
    pull_policy: "always"
    ports:
      - "10101:9999"
    environment:
      - TREETOP_LISTEN=0.0.0.0
      - TREETOP_PORT=9999
      - TREETOP_CLIENT_ALLOWLIST=*
      - TREETOP_POLICY_URL=http://integration-test-cedar-server:18999/dns.cedar
      - TREETOP_LABELS_URL=http://integration-test-cedar-server:18999/labels.json
      - TREETOP_POLICY_UPDATE_FREQUENCY=120
      - TREETOP_LABELS_UPDATE_FREQUENCY=120
    depends_on:
      - integration-test-cedar-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/api/v1/health"]
      interval: 2s
